//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("SoftThorn")]
[assembly: AssemblyProduct("MonstercatNet")]
[assembly: AssemblyCopyright("© 2023 Insire")]
[assembly: AssemblyTrademark("")]

// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("CompileDate", "[UTC]11.12.2023 21:00:56")]
[assembly: AssemblyMetadata("PublicRelease", "False")]
[assembly: AssemblyMetadata("Branch", "drop_newtonsoftjson")]
[assembly: AssemblyMetadata("Commit", "4f9f78afb8ccaa5a9e52eabe1f25aa5005f228de")]
[assembly: AssemblyMetadata("Version", "3.0.50-g4f9f78afb8")]
