//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("SoftThorn")]
[assembly: AssemblyProduct("MonstercatNet")]
[assembly: AssemblyCopyright("© 2020 Insire")]
[assembly: AssemblyTrademark("")]

// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("CompileDate", "[UTC]20.09.2020 10:12:57")]
[assembly: AssemblyMetadata("PublicRelease", "True")]
[assembly: AssemblyMetadata("Branch", "master")]
[assembly: AssemblyMetadata("Commit", "79a03140dcb0cc811ab11d81b6ac5d98cdf45dad")]
[assembly: AssemblyMetadata("Version", "2.0.12")]
