//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by Cake.
// </auto-generated>
//------------------------------------------------------------------------------
using System.Reflection;

[assembly: AssemblyCompany("SoftThorn")]
[assembly: AssemblyProduct("MonstercatNet")]
[assembly: AssemblyCopyright("© 2020 Insire")]
[assembly: AssemblyTrademark("")]

// Metadata Attributes
[assembly: AssemblyMetadata("Platform", "AnyCPU")]
[assembly: AssemblyMetadata("CompileDate", "[UTC]13.09.2020 17:26:33")]
[assembly: AssemblyMetadata("PublicRelease", "False")]
[assembly: AssemblyMetadata("Branch", "master")]
[assembly: AssemblyMetadata("Commit", "8260858bbb8b6a5ec3ec35d2e491b18183ffae89")]
